// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaTesourariaEclesiastica.Data;

#nullable disable

namespace SistemaTesourariaEclesiastica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.CentroCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CentrosCusto");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.DetalheFechamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("FechamentoPeriodoId")
                        .HasColumnType("int");

                    b.Property<string>("Fornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MeioPagamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Membro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PlanoContas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FechamentoPeriodoId");

                    b.ToTable("DetalhesFechamento");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.DevolucaoEmprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDevolucao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EmprestimoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("ValorDevolvido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmprestimoId")
                        .HasDatabaseName("IX_DevolucaoEmprestimos_EmprestimoId");

                    b.ToTable("DevolucaoEmprestimos");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataQuitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataEmprestimo")
                        .IsDescending()
                        .HasDatabaseName("IX_Emprestimos_DataEmprestimo");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Emprestimos_Status");

                    b.HasIndex("Status", "DataEmprestimo")
                        .HasDatabaseName("IX_Emprestimos_Status_DataEmprestimo");

                    b.ToTable("Emprestimos");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<string>("ComprovanteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MeioDePagamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("MembroId")
                        .HasColumnType("int");

                    b.Property<int?>("ModeloRateioEntradaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlanoDeContasId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.HasIndex("MeioDePagamentoId");

                    b.HasIndex("MembroId");

                    b.HasIndex("ModeloRateioEntradaId");

                    b.HasIndex("PlanoDeContasId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.FechamentoPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("int");

                    b.Property<decimal>("BalancoDigital")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BalancoFisico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataProcessamentoPelaSede")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSubmissao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FechamentoSedeProcessadorId")
                        .HasColumnType("int");

                    b.Property<bool>("FoiProcessadoPelaSede")
                        .HasColumnType("bit");

                    b.Property<int?>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("SaldoFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoFechamento")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalEntradas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalEntradasDigitais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalEntradasFisicas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalRateios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalSaidas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalSaidasDigitais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalSaidasFisicas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("UsuarioAprovacaoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioSubmissaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.HasIndex("FechamentoSedeProcessadorId");

                    b.HasIndex("UsuarioAprovacaoId");

                    b.HasIndex("UsuarioSubmissaoId");

                    b.ToTable("FechamentosPeriodo");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CEP")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.ItemRateioFechamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FechamentoPeriodoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RegraRateioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRateio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FechamentoPeriodoId");

                    b.HasIndex("RegraRateioId");

                    b.ToTable("ItensRateioFechamento");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.LogAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.MeioDePagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TipoCaixa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("MeiosDePagamento");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Membro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apelido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("CentroCustoId");

                    b.ToTable("Membros");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.ModeloRateioEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PercentualCongregacao")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PercentualSede")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ModelosRateioEntrada");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.PlanoDeContas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("PlanosDeContas");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.RegraRateio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CentroCustoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("CentroCustoOrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoDestinoId");

                    b.HasIndex("CentroCustoOrigemId");

                    b.ToTable("RegrasRateio");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Saida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroCustoId")
                        .HasColumnType("int");

                    b.Property<string>("ComprovanteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<int>("MeioDePagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlanoDeContasId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDespesa")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("MeioDePagamentoId");

                    b.HasIndex("PlanoDeContasId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Saidas");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.TransferenciaInterna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroCustoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("CentroCustoOrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MeioDePagamentoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("MeioDePagamentoOrigemId")
                        .HasColumnType("int");

                    b.Property<bool>("Quitada")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoDestinoId");

                    b.HasIndex("CentroCustoOrigemId");

                    b.HasIndex("MeioDePagamentoDestinoId");

                    b.HasIndex("MeioDePagamentoOrigemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TransferenciasInternas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.ApplicationUser", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCusto")
                        .WithMany("Usuarios")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CentroCusto");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.ContaBancaria", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCusto")
                        .WithMany("ContasBancarias")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroCusto");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.DetalheFechamento", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.FechamentoPeriodo", "FechamentoPeriodo")
                        .WithMany("DetalhesFechamento")
                        .HasForeignKey("FechamentoPeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FechamentoPeriodo");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.DevolucaoEmprestimo", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.Emprestimo", "Emprestimo")
                        .WithMany("Devolucoes")
                        .HasForeignKey("EmprestimoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprestimo");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Entrada", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCusto")
                        .WithMany("Entradas")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.MeioDePagamento", "MeioDePagamento")
                        .WithMany("Entradas")
                        .HasForeignKey("MeioDePagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.Membro", "Membro")
                        .WithMany("Entradas")
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaTesourariaEclesiastica.Models.ModeloRateioEntrada", "ModeloRateioEntrada")
                        .WithMany("Entradas")
                        .HasForeignKey("ModeloRateioEntradaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaTesourariaEclesiastica.Models.PlanoDeContas", "PlanoDeContas")
                        .WithMany("Entradas")
                        .HasForeignKey("PlanoDeContasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroCusto");

                    b.Navigation("MeioDePagamento");

                    b.Navigation("Membro");

                    b.Navigation("ModeloRateioEntrada");

                    b.Navigation("PlanoDeContas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.FechamentoPeriodo", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCusto")
                        .WithMany("FechamentosPeriodo")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.FechamentoPeriodo", "FechamentoSedeProcessador")
                        .WithMany("FechamentosCongregacoesIncluidos")
                        .HasForeignKey("FechamentoSedeProcessadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", "UsuarioAprovacao")
                        .WithMany()
                        .HasForeignKey("UsuarioAprovacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", "UsuarioSubmissao")
                        .WithMany()
                        .HasForeignKey("UsuarioSubmissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroCusto");

                    b.Navigation("FechamentoSedeProcessador");

                    b.Navigation("UsuarioAprovacao");

                    b.Navigation("UsuarioSubmissao");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.ItemRateioFechamento", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.FechamentoPeriodo", "FechamentoPeriodo")
                        .WithMany("ItensRateio")
                        .HasForeignKey("FechamentoPeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.RegraRateio", "RegraRateio")
                        .WithMany("ItensRateio")
                        .HasForeignKey("RegraRateioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FechamentoPeriodo");

                    b.Navigation("RegraRateio");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.LogAuditoria", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Membro", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCusto")
                        .WithMany("Membros")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroCusto");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.RegraRateio", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCustoDestino")
                        .WithMany()
                        .HasForeignKey("CentroCustoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCustoOrigem")
                        .WithMany()
                        .HasForeignKey("CentroCustoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroCustoDestino");

                    b.Navigation("CentroCustoOrigem");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Saida", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCusto")
                        .WithMany("Saidas")
                        .HasForeignKey("CentroCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.Fornecedor", "Fornecedor")
                        .WithMany("Saidas")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaTesourariaEclesiastica.Models.MeioDePagamento", "MeioDePagamento")
                        .WithMany("Saidas")
                        .HasForeignKey("MeioDePagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.PlanoDeContas", "PlanoDeContas")
                        .WithMany("Saidas")
                        .HasForeignKey("PlanoDeContasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroCusto");

                    b.Navigation("Fornecedor");

                    b.Navigation("MeioDePagamento");

                    b.Navigation("PlanoDeContas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.TransferenciaInterna", b =>
                {
                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCustoDestino")
                        .WithMany("TransferenciasDestino")
                        .HasForeignKey("CentroCustoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.CentroCusto", "CentroCustoOrigem")
                        .WithMany("TransferenciasOrigem")
                        .HasForeignKey("CentroCustoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.MeioDePagamento", "MeioDePagamentoDestino")
                        .WithMany("TransferenciasDestino")
                        .HasForeignKey("MeioDePagamentoDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.MeioDePagamento", "MeioDePagamentoOrigem")
                        .WithMany("TransferenciasOrigem")
                        .HasForeignKey("MeioDePagamentoOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaTesourariaEclesiastica.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroCustoDestino");

                    b.Navigation("CentroCustoOrigem");

                    b.Navigation("MeioDePagamentoDestino");

                    b.Navigation("MeioDePagamentoOrigem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.CentroCusto", b =>
                {
                    b.Navigation("ContasBancarias");

                    b.Navigation("Entradas");

                    b.Navigation("FechamentosPeriodo");

                    b.Navigation("Membros");

                    b.Navigation("Saidas");

                    b.Navigation("TransferenciasDestino");

                    b.Navigation("TransferenciasOrigem");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Emprestimo", b =>
                {
                    b.Navigation("Devolucoes");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.FechamentoPeriodo", b =>
                {
                    b.Navigation("DetalhesFechamento");

                    b.Navigation("FechamentosCongregacoesIncluidos");

                    b.Navigation("ItensRateio");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Fornecedor", b =>
                {
                    b.Navigation("Saidas");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.MeioDePagamento", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("Saidas");

                    b.Navigation("TransferenciasDestino");

                    b.Navigation("TransferenciasOrigem");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.Membro", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.ModeloRateioEntrada", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.PlanoDeContas", b =>
                {
                    b.Navigation("Entradas");

                    b.Navigation("Saidas");
                });

            modelBuilder.Entity("SistemaTesourariaEclesiastica.Models.RegraRateio", b =>
                {
                    b.Navigation("ItensRateio");
                });
#pragma warning restore 612, 618
        }
    }
}
